export const WORLD = {
    CHUNK_SIZE: 16,
    CHUNK_HEIGHT: 128,
    RENDER_DISTANCE: 4,
    GRAVITY: -0.015,
    JUMP_FORCE: 0.52,
    WALK_SPEED: 4.317,
    SPRINT_SPEED: 5.612,
    SNEAK_SPEED: 1.295
};

export enum BLOCK_TYPE {
    AIR = 0,
    GRASS = 1,
    DIRT = 2,
    STONE = 3,
    LOG = 4,
    LEAVES = 5,
    WATER = 6,
    GLASS = 7,
    GLOWSTONE = 8,
    PLANKS = 9,
    BRICK = 10,
    CRAFTING_TABLE = 11,
    SAND = 12,
    COBBLESTONE = 13,
    DIAMOND_ORE = 14,
    COAL_ORE = 15,
    IRON_ORE = 16,
    GOLD_ORE = 17,
    TNT = 18,
    FURNACE = 19,
    FLOWER_RED = 20,
    FLOWER_YELLOW = 21,
    TALL_GRASS = 22
}

// Block hardness (seconds to break with hand)
export const BLOCK_HARDNESS: Record<number, number> = {
    [BLOCK_TYPE.GRASS]: 0.6,
    [BLOCK_TYPE.DIRT]: 0.5,
    [BLOCK_TYPE.STONE]: 1.5,
    [BLOCK_TYPE.LOG]: 0.8,
    [BLOCK_TYPE.LEAVES]: 0.2,
    [BLOCK_TYPE.GLASS]: 0.3,
    [BLOCK_TYPE.GLOWSTONE]: 0.3,
    [BLOCK_TYPE.PLANKS]: 0.8,
    [BLOCK_TYPE.BRICK]: 2.0,
    [BLOCK_TYPE.CRAFTING_TABLE]: 0.8,
    [BLOCK_TYPE.SAND]: 0.5,
    [BLOCK_TYPE.COBBLESTONE]: 1.5,
    [BLOCK_TYPE.DIAMOND_ORE]: 3.0,
    [BLOCK_TYPE.COAL_ORE]: 1.2,
    [BLOCK_TYPE.IRON_ORE]: 1.5,
    [BLOCK_TYPE.GOLD_ORE]: 2.0,
    [BLOCK_TYPE.TNT]: 0.0, // Instant
    [BLOCK_TYPE.FURNACE]: 1.2,
    [BLOCK_TYPE.FLOWER_RED]: 0.0,
    [BLOCK_TYPE.FLOWER_YELLOW]: 0.0,
    [BLOCK_TYPE.TALL_GRASS]: 0.0,
};

export const BLOCK_NAMES: Record<number, string> = {
    [BLOCK_TYPE.GRASS]: 'Grass',
    [BLOCK_TYPE.DIRT]: 'Dirt',
    [BLOCK_TYPE.STONE]: 'Stone',
    [BLOCK_TYPE.LOG]: 'Oak Log',
    [BLOCK_TYPE.LEAVES]: 'Leaves',
    [BLOCK_TYPE.WATER]: 'Water',
    [BLOCK_TYPE.GLASS]: 'Glass',
    [BLOCK_TYPE.GLOWSTONE]: 'Glowstone',
    [BLOCK_TYPE.PLANKS]: 'Oak Planks',
    [BLOCK_TYPE.BRICK]: 'Bricks',
    [BLOCK_TYPE.CRAFTING_TABLE]: 'Craft Table',
    [BLOCK_TYPE.SAND]: 'Sand',
    [BLOCK_TYPE.COBBLESTONE]: 'Cobblestone',
    [BLOCK_TYPE.DIAMOND_ORE]: 'Diamond Ore',
    [BLOCK_TYPE.COAL_ORE]: 'Coal Ore',
    [BLOCK_TYPE.IRON_ORE]: 'Iron Ore',
    [BLOCK_TYPE.GOLD_ORE]: 'Gold Ore',
    [BLOCK_TYPE.TNT]: 'TNT',
    [BLOCK_TYPE.FURNACE]: 'Furnace',
    [BLOCK_TYPE.FLOWER_RED]: 'Rose',
    [BLOCK_TYPE.FLOWER_YELLOW]: 'Dandelion',
    [BLOCK_TYPE.TALL_GRASS]: 'Tall Grass',
};

// All placeable block types (for creative inventory)
export const ALL_BLOCKS = [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22];

export const BLOCK_COLORS: Record<number, number> = {
    [BLOCK_TYPE.GRASS]: 0x79b65d,
    [BLOCK_TYPE.DIRT]: 0x866043,
    [BLOCK_TYPE.STONE]: 0x7c7c7c,
    [BLOCK_TYPE.LOG]: 0x675231,
    [BLOCK_TYPE.LEAVES]: 0x2d6e1e,
    [BLOCK_TYPE.WATER]: 0x3f76e4,
    [BLOCK_TYPE.GLASS]: 0xddeeff,
    [BLOCK_TYPE.GLOWSTONE]: 0xfdfd72,
    [BLOCK_TYPE.PLANKS]: 0xb8945f,
    [BLOCK_TYPE.BRICK]: 0x964b33,
    [BLOCK_TYPE.CRAFTING_TABLE]: 0x8b6e4f,
    [BLOCK_TYPE.SAND]: 0xdbc67b,
    [BLOCK_TYPE.COBBLESTONE]: 0x888888,
    [BLOCK_TYPE.DIAMOND_ORE]: 0x5de2e8,
    [BLOCK_TYPE.COAL_ORE]: 0x333333,
    [BLOCK_TYPE.IRON_ORE]: 0xd8af93,
    [BLOCK_TYPE.GOLD_ORE]: 0xfcee4b,
    [BLOCK_TYPE.TNT]: 0xff2200,
    [BLOCK_TYPE.FURNACE]: 0x6b6b6b,
    [BLOCK_TYPE.FLOWER_RED]: 0xff1111,
    [BLOCK_TYPE.FLOWER_YELLOW]: 0xffdd00,
    [BLOCK_TYPE.TALL_GRASS]: 0x5a9e3a,
};
